### PR TITLE
Remove unneeded sub `cfg` with only one condition

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes current failures in CI.

### CODE REVIEW

**Comment by partim** [comment]
> error: package `time v0.3.27` cannot be built because it requires rustc 1.67.0 or newer

Ah, lovely. I wish fundamental libraries wouldn’t do this sort of thing. I guess we’ll have to move to 1.67.0 then.

**Comment by WhyNotHugo** [comment]
> time is guaranteed to compile with the latest stable release of Rust in addition to the two prior minor releases. For example, if the latest stable Rust release is 1.70, then time is guaranteed to compile with Rust 1.68, 1.69, and 1.70.

From: https://github.com/time-rs/time

If you want to keep an MSRV of 1.67.0, you're going to need to pin an older version of the `time` library.

**Comment by WhyNotHugo** [comment]
time v0.3.23 is the last version to support Rust 1.65.0

**Comment by partim** [comment]
Not sure pinning the version is a good idea – you would want to use the newest version if your compiler supports it. For now, upgrading the minimal Rust version to 1.67 is probably better.

**Comment by WhyNotHugo** [comment]
Sure. Note that the latest version is not guaranteed to work with 1.67.0, it does so by mere fortune and this might change any time.

**Comment by WhyNotHugo** [comment]
All green!

image

**Comment by partim** [comment]
> Sure. Note that the latest version is not guaranteed to work with 1.67.0, it does so by mere fortune and this might change any time.

Yeah. I think this is mostly an issue for the CI where we test that the promised MSRV actually works. Maybe we should change that into a `cargo check` with the oldest possible library versions. (I think there was a cargo thing for that, have to dig it up.)

**Comment by partim** [comment]
Anyhow, thanks for the PR! Looking good!

**Pull request merged**
