### PR TITLE
base/flags: add utility type Flags

### LINKED ISSUE #108: utility struct for flags
I'd find it useful if there was a single struct containing the flags from the message header. It'd also be useful if it had a text representation, e.g. "QR AA" and if the struct could be constructed from this string representation as well.

I'd use the same string representation as the dnspython library: https://github.com/rthalley/dnspython/blob/master/dns/flags.py

For now, I'd stick with standard flags only (ignoring EDNS flags), which can be easily constructed from header.

Would this feature make sense to you? If so, I could contribute the code.

### PR DESCRIPTION
**Pull request by tomaskrizek**
The Flags type simplifies working with all flags, e.g. making it easier
to compare, hash or represent them as string.

The string notation is consistent with dnspython library
(https://github.com/rthalley/dnspython/blob/master/dns/flags.py).

Fixes #108

### CODE REVIEW

**Comment by partim** [comment]
Thanks for the PR. It is looking good!

However, I think I’d prefer to have the `Flags` type be part of the `headers` module instead of having a separate module.

**Comment by tomaskrizek** [comment]
I had the `Flags` as part of `header` module at first, but when I had to create the extra `FromStrError` type, it seemed better to put it in a separate namespace. Wouldn't it be confusing to have this type in the `header` module as well?

**Comment by partim** [comment]
I think `FlagsFromStrError` is perfectly fine. It’s not like people will have to type the name all that often.

**Comment by tomaskrizek** [comment]
Ok, thanks for the suggestion. I've renamed the error type and moved everything into the `header` module.

**Pull request merged**
