### PR TITLE
Implement std::error::Error for SrvError

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Fixes: https://github.com/NLnetLabs/domain/issues/181

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Any thoughts on using [`thiserror`](https://docs.rs/thiserror/latest/thiserror/) instead? It could reduce quite some overhead

**Comment by partim** [comment]
I think for a library having fewer dependencies at the price of having the add a few more boilerplate manually is an okay trade-off.

**Comment by WhyNotHugo** [comment]
Updated. Also replaced `std::fmt::Formatter` with just `fmt::Formatter`.

**Comment by partim** [comment]
Thank you! Looks good to go now!

**Pull request merged**
