### PR TITLE
domain/octets: implement Convert trait to allow converting octet types

### PR DESCRIPTION
**Pull request by vavrusa**
This trait forms a basis for converting structured types built on top
of octets such as CharStr, Dname, RDATA, and Record types.

#68

### CODE REVIEW

**Comment by partim** [comment]
Could we get away with using `TryFrom` with references as sources instead of having a new trait? The trait bounds might get a bit messy, but so far all those mad bounds for octets types have been surprisingly invisible for users.

**Comment by vavrusa** [comment]
I can add it as a convenience trait, would that work for you? Having the implementation for octets conversion in a specific method is good as it's clear in what it does (octets conversion), whereas TryFrom is a generic conversion from anything to anything.

**Comment by partim** [comment]
After thinking about it properly (I blame the heat), you are, of course, correct that we want a dedicated trait.

I wonder now, though, if the blanket impl under certain conditions is a good idea or if it (because of specialisation rules) may prohibit optimizations for certain pairs or even block out-of-crate implementation completely.

**Comment by vavrusa** [comment]
Right, this:

```
impl<Octets, Target> Convert<Target> for Octets
where
    Octets: AsRef<[u8]>,
    Target: FromBuilder,
    <Target as FromBuilder>::Builder: EmptyBuilder
{
    fn convert(&self) -> Result<Target, ShortBuf> {
        self.as_ref().to_octets()
    }
}
```

I'm not sure how to implement it better. Implement it for combinations of &[u8], Cow<&[u8]>, Vec<u8>, Bytes<u8>, BytesMut<u8>?

**Comment by partim** [comment]
Implementing it specifically for each target type but if possible using generic sources might work best? I.e., have a specific impl for `&[u8]` that accepts anything that is `AsRef<[u8]>` and so on.

It also now occurs to me that the name of the trait should probably be more specific, e.g. `ConvertOctets`, since traits are normally imported by name only and not qualified by their module. So I think we should indicate in the name itself that the trait is specific for converting octet sequences.

**Comment by partim** [comment]
So turns out I was confused about the direction of `ConvertOctets` in my earlier remark. That's a good indication that the name is bad. Perhaps we should call it `IntoOctets` and also have a `FromOctets`?

Looking at your impls for `Dname<_>`, I wonder if we should drop the trait bounds from the type definition. That would make things like `IntoOctets` (and probably more trait impls) much more compact.

**Comment by vavrusa** [comment]
What do you want to do about existing `IntoOctets` trait?

**Comment by partim** [comment]
Sorry, I should look at these things properly before responding.

Do we need to have the current `IntoOctets` as a separate trait from `OctetsBuilder`. Asked differently, is there a use case for an octets builder that cannot impl current `IntoOctets` for any reason? All the octets builders we have right now also implement `IntoOctets`.

So, unless there is a reason to keep this split, I think merging current `IntoOctets` into `OctetsBuilder` and then reusing the name for a new `IntoOctets` trait might be a good path forward. I think this will also bring the interface more in line with common use where the Into traits carry their target as a type parameter and not an associated type.

The merging should probably be in a separate PR. I'm happy to do that if you agree with this approach.

**Comment by vavrusa** [comment]
Ok, that sounds reasonable.

**Comment by partim** [comment]
I’ve merged the trait in #75.

**Comment by partim** [comment]
That last commit should probably be in its own PR.

Since this is all a bit messy now, do you want to continue with this PR or do you want me to take it over?

**Comment by vavrusa** [comment]
Ah sorry this is from my main branch, let me open a separate PR for the bugfixes. If you have time to finish the Convert trait that'd be great, I can get back to it next week otherwise.

**Comment by vavrusa** [comment]
I moved bugfixes to https://github.com/NLnetLabs/domain/pull/76 and rebased this to master.

**Comment by partim** [comment]
I’ll try to get a new PR for the conversion traits submitted by tomorrow CET evening.

**Comment by partim** [comment]
So I drafted a version that, similarly to the standard `From` and `Into` moves the sources into the target. That is fine for converting from a type atop a `Vec<u8>` to, say, `Bytes`, but we’d still need to provide a non-trait `for_ref` and `for_slice`. I don’t quite mind that, but does that work for your use cases?

I also just realized that `from_octets` is commonly used as the name of the associated function that creates a thing from a raw octets sequence. I don’t really want to change that (again), since it is all over the place. So we need a better name for those traits.

**Comment by partim** [comment]
Maybe flip it around? `OctetsFrom` and `OctetsInto`? That would express that we are indeed only converting octets and nothing else?

**Comment by vavrusa** [comment]
> So I drafted a version that, similarly to the standard From and Into moves the sources into the target.

It should be ok either way. I've added some test cases for conversions here so if those pass it'll likely work unless there's some complications propagating the new trait bounds.

> Maybe flip it around? OctetsFrom and OctetsInto?

It's ok, it might be confusing with `from()` and `from_octets()`. I kind of liked the `ConvertOctets` naming because it implies converting from one octets into another and not just from octets to something else. But it doesn't describe direction sufficiently.

**Comment by partim** [comment]
I am not quite happy with the names either but I suspect there is no perfect solution here.

Meanwhile, I suggest we continue in PR #77.

**Comment by partim** [comment]
This PR has been solved in #77 and I believe can be closed.

**Pull request closed without merging**
