### PR TITLE
Minor fix for 0.10.0

### PR DESCRIPTION
**Pull request by xofyarg**
Hi, I included two trivial changes when working on an upgrade from domain-0.7 to 0.10. Please let me know if I missed anything. Thanks.

### CODE REVIEW

**Comment by partim** [comment]
Thank you for the PR!

I am wondering if the type bitmap can ever be empty? Given that both RRSIG and NSEC(3) seem to be included in it, there should at least be the NSEC(3) record set?

**Comment by Philip-NLnetLabs** [comment]
The NSEC3 bitmap has all of the records present at the owner name, which is empty for an empty non-terminal.

**Comment by partim** [comment]
Ah, right. I suppose the PR can be merge, then.

**Review by partim — APPROVED** [review]

**Comment by xofyarg** [comment]
I had the same question, and my colleague pointed me at this one:

> ... the NSEC3 RR exists because it corresponds to an empty non-terminal, in which case the NSEC3 RR will have an empty Type Bit Maps field

https://datatracker.ietf.org/doc/html/rfc5155#section-8.5

**Pull request merged**
