### PR TITLE
base/message_builder: fix writing of option codes with the new OptBuilder

### PR DESCRIPTION
**Pull request by vavrusa**
The option length wasn't written previously.

### CODE REVIEW

**Comment by partim** [comment]
Oops. Sorry about that … I really need to add tests all over the place.

There now is `OctetsBuilder::u16_len_prefixed`, though, which you probably should use for this purpose.

**Comment by vavrusa** [comment]
That's awesome, I'll use that.

**Comment by partim** [comment]
I really did mean myself with the note on adding tests, but thank you nonetheless!

**Comment by vavrusa** [comment]
Do you mind making a new release?

**Comment by partim** [comment]
Done!

Didn’t do `domain-resolv`, though, since nothing has changed.

**Comment by vavrusa** [comment]
Thanks!

**Pull request merged**
