### PR TITLE
domain-resolv: allow a different canonical name in FoundHostsIter

### PR DESCRIPTION
**Pull request by vavrusa**
Each message may resolve to a different canonical name, so calculating it
only from the first response might cause records to be ignored in the second
response.

### CODE REVIEW

**Comment by partim** [comment]
Thank you for the PR!

As the CI failure is mostly related to newly introduced Clippy lints, could you merge master into your branch to get it to “green” before merging?

**Comment by vavrusa** [comment]
Yes of course, happy to get to work on domain again!

**Comment by vavrusa** [comment]
Thanks! Are you planning to tag a release any time soon, or should I keep using the revision for now?

**Comment by partim** [comment]
I was planning on doing a release today but then caught up in cleaning up the documentation. Expect 0.6.0 on Monday.

**Pull request merged**
