### PR TITLE
Merge tag 'v0.7.2'

### PR DESCRIPTION
**Pull request by WhyNotHugo**
v0.7.2 contained fixed that were never ported to the main branch, and
lost in the v0.8.0 release.

Merge this branch to introduce both the changes themselves and retain
their history.

Fixes: https://github.com/NLnetLabs/domain/issues/213

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
I've resolved all conflicts in this branch and only retained the bits that were _actually_ lost. Hence the relatively short diff.

**Comment by partim** [comment]
Thanks for the PR! I could have sworn I also added this to main. My apologies!

**Comment by WhyNotHugo** [comment]
Do you mind publishing a v0.8.1 tag with this change? The fixes in e81ce5885be1f0f9d3f55f6c0c70b588e4d3a1a8 are also missing from v0.8.0.

**Comment by partim** [comment]
Will do! I’ll merge the remaining open PRs and then make a release.

**Pull request merged**
