### PR TITLE
Don't run CI checks twice per push to PR branches.

### PR DESCRIPTION
**Pull request by ximon18**
We currently suffer from this: https://github.com/orgs/community/discussions/26940

This PR hopes to prevent this dual execution of the same checks per PR commit.

### CODE REVIEW

**Comment by bal-e** [comment]
From what I understand, the `pull_request` version will merge the branch to `main` (or whatever the target branch is) before running the tests.  This is an important distinction from the `push` version, since some bugs are caused by freshly-merged PRs that the PR being tested did not integrate yet.  I ran into this case with the `ZonefileFmt` PR, which changed a `Display` impl I was relying upon at some point.

**Comment by bal-e** [comment]
Looking at the CI failure: Should `unstable-server-transport` enable the `unstable-client-transport` feature?

**Comment by ximon18** [comment]
> Looking at the CI failure: Should `unstable-server-transport` enable the `unstable-client-transport` feature?

I would have expected that to be fixed by #432. Perhaps this PR just needs rebasing against/merging with `main`. I'll check.

**Comment by ximon18** [comment]
True, so we could use `pull_request` instead of `push` but then the CI would not be run for commits to branches that don't yet have a PR associated with them (which is maybe fine, you can always create a draft PR if you're not ready yet but want CI feedback).

**Review by bal-e — APPROVED** [review]
LGTM!

**Review by partim — APPROVED** [review]

**Pull request merged**
