### PR TITLE
Mark function without side effects as must_use

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This hint will make the compiler warn consumers of this library if they ever call one of these functions without using its return value.

### CODE REVIEW

**Comment by partim** [comment]
Thank you for the PR!

Is this idiomatic use of the `#[must_use]` attribute? I so far only considered it for cases where ignoring the return type likely results in problems not merely waste.

**Comment by WhyNotHugo** [comment]
> I so far only considered it for cases where ignoring the return type likely results in problems not merely waste.

The docs aren't too specific:

https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

The places where it's used here are functions that have no side effect but construct a new value. Calling them without using the return value is usually a programmer mistake (it should either be assigned or the call deleted entirely).

**Comment by partim** [comment]
Hm. You are certainly correct. And I suppose this isn’t all that different from the unused variables warnings.

I’ll merge it. But, I think this is a breaking change, so I’ll stick the label on it and keep it open until we get closer to a breaking release. (I am trying to avoid the issues we had with having to forward port changes.)

**Comment by WhyNotHugo** [comment]
Exactly! It's more a hint that anything else.

I don't think that it's breaking; at most, consumers will see a warning. And this is in case they're doing something like `CharStr::builder();` without assigning the builder to any variable.

**Comment by partim** [comment]
It might not strictly be breaking, but it has the potential to break CI runs without any changes and I really detest that.

**Comment by WhyNotHugo** [comment]
It's your call, this is trivial to rebase anyway.

**Pull request merged**
