### PR TITLE
Add support for RFC 8914

### PR DESCRIPTION
**Pull request by xofyarg**
This change adds Extended DNS Error support into opt module.

### CODE REVIEW

**Comment by partim** [comment]
Thank you for the PR! It is looking good.

Perhaps it would be a good idea to move the `Code` enum into the `base::iana` module where all the IANA managed definitions already live, perhaps as `base::iana::exterr::ExtendedError`? That way we could reuse the macros already defined for defining these enums with all the methods and impls. The purpose string from the registry can go where the mnemonics normally live.

**Comment by xofyarg** [comment]
I've separated the definitions and logic, please take another look.

Although the EXTRA-TEXT is not used very often, the `fmt::Display` should include it. So I didn't use any macro on `iana::ExtendedErrorCode`, but implement it on `opt::ExtendedError`.

**Comment by partim** [comment]
Looking great now, I’d be happy to merge it. Thanks again for the PR!

We could probably manually impl `Display` for `ExtendedErrorCode` as well – it just needs to call `to_mnemonic`. Do you want to add that or are you fine the way it is and want me to merge? Either way is fine with me.

**Comment by xofyarg** [comment]
Sure, I can add something like below:
```
int_enum_str_with_prefix!(ExtendedErrorCode, "EDE", b"EDE", u16, "unknown ede code");  
```

BTW, I wonder why the mnemonic is stored as `&'static [u8]` instead of `&'static str`. It makes some functions trying to convert it to utf8 unnecessarily like in `Display`. I had some benchmarks:

```
use super::super::octets::Octets512;
pub struct B1(pub ExtendedError<Octets512>);
impl fmt::Display for B1 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self.0.code.to_mnemonic() {
            Some(m) => {
                for ch in m {
                    f.write_char(*ch as char)?
                }
            }
            None => write!(f, "Undefined({})", self.0.code.to_int())?,
        }

        if let Some(text) = &self.0.text {
            let text = str::from_utf8(text.as_ref()).map_err(|_| fmt::Error)?;
            write!(f, " ({})", text)?;
        }
        Ok(())
    }
}

pub struct B2(pub ExtendedError<Octets512>);
impl fmt::Display for B2 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.0.code.fmt(f)?;

        if let Some(text) = &self.0.text {
            let text = str::from_utf8(text.as_ref()).map_err(|_| fmt::Error)?;
            write!(f, " ({})", text)?;
        }
        Ok(())
    }
}

pub struct B3(pub ExtendedError<Octets512>);
impl fmt::Display for B3 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self.0.code.to_mnemonic() {
            Some(m) => f.write_str(unsafe { str::from_utf8_unchecked(m) })?,
            None => write!(f, "Undefined({})", self.0.code.to_int())?,
        }

        if let Some(text) = &self.0.text {
            let text = str::from_utf8(text.as_ref()).map_err(|_| fmt::Error)?;
            write!(f, " ({})", text)?;
        }
        Ok(())
    }
}
```

```
ede_display             time:   [166.57 ns 167.09 ns 167.66 ns]
Found 5 outliers among 100 measurements (5.00%)
  2 (2.00%) high mild
  3 (3.00%) high severe

ede_display_via_code    time:   [206.98 ns 207.29 ns 207.62 ns]
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) high mild
  3 (3.00%) high severe

ede_display_fast        time:   [48.441 ns 48.892 ns 49.395 ns]
Found 31 outliers among 100 measurements (31.00%)
  15 (15.00%) low severe
  2 (2.00%) low mild
  4 (4.00%) high mild
  10 (10.00%) high severe
```

**Comment by partim** [comment]
`int_enum_str_with_prefix!` also adds an impl for `FromStr` which, I think, we don’t really want here. Maybe just impl `Display` directly for now?

I think the decision to make mnemonics `[u8]`s and not `str`s was because they are always ASCII. I wouldn’t mind switching them to `str`.

This is a breaking change, though, so would be wait at least until 0.6. I have plans to revisit zone file reading and writing as that is fairly slow today, too. That would be a good occasion.

**Comment by xofyarg** [comment]
OK, using directly implementation for `Display` now.

**Comment by partim** [comment]
Thank you once again for the PR!

**Pull request merged**
